 AWSTemplateFormatVersion: "2010-09-09"
 Parameters:
   DomainName:
     Type: String
     Default: example.net
   TTL:
     Type: Number
     Default: 600
   ApexRecords:
     Type: CommaDelimitedList
     Description: >-
       The default here is for GitHub Pages, cf
       https://help.github.com/articles/setting-up-an-apex-domain/
     Default: 192.30.252.153,192.30.252.154
 Resources:
   Zone:
     Type: 'AWS::Route53::HostedZone'
     Properties:
       Name: !Ref DomainName
       HostedZoneConfig:
 	Comment: !Join
 	  - " "
 	  - ["My hosted zone for", !Ref DomainName]
   ApexRecordSet:
     Type: 'AWS::Route53::RecordSet'
     Properties:
       Name: !Ref DomainName
       HostedZoneId: !Ref Zone
       Type: A
       TTL: !Ref TTL
       ResourceRecords: !Ref ApexRecords
