version: '3.6'

services:
  nginx-rtmp:
    build:
      context: .
      network: 'host'
    ports:
      - ${RTMP_PORT:-1935}:1935
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - RTMP_PORT=1935
      # set a custom auth token here
      - RTMP_AUTH_TOKEN=${RTMP_AUTH_TOKEN:-}
      - SSL_ENABLED=${SSL_ENABLED:-false}
      - DOMAIN=${DOMAIN:-}
      - EMAIL=${EMAIL:-}
      - RENEW_INTERVAL=${RENEW_INTERVAL:-1h}
      - RTMP_AUTH_URL=${RTMP_AUTH_URL:-http://127.0.0.1:80/auth}
      # set custom ffmpeg flags here      - DOMAIN=${DOMAIN:-}
      #
      # example with multiple adaptation sets:
      #- FFMPEG_FLAGS=-window_size 100 -max_muxing_queue_size 1000 -map 0:v:0 -map 0:a\?:0 -map 0:v:0 -map 0:a\?:0 -b:v:0 350k -c:v:0 libx264 -filter:v:0 "scale=320:-1" -b:v:1 1000k -c:v:1 libx264 -filter:v:1 "scale=640:-1" -adaptation_sets "id=0,streams=v id=1,streams=a"
      #
      - FFMPEG_FLAGS=-window_size 100 -max_muxing_queue_size 1000 -c:v copy
    env_file:
     - ./.env
    networks:
      - emp-network
    tmpfs:
      - /dash
  rtmp-tester:
    build:
      context: ./tester/
      network: 'host'
    command: /run-tests.sh
    environment:
      # must match auth token above
      - RTMP_AUTH_TOKEN=${RTMP_AUTH_TOKEN:-}
      - SSL_ENABLED=${SSL_ENABLED:-false}
    env_file:
     - ./.env
    depends_on:
      - nginx-rtmp
    networks:
      - emp-network


networks:
  emp-network:
    driver: bridge
