branch-defaults:
  cf-impl:
    environment: earshot-test-8
environment-defaults:
  earshot-test-8:
    branch: null
    repository: null
global:
  application_name: earshot-test
  branch: null
  default_ec2_keyname: ecs-test
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: roddy
  repository: null
  sc: git
  workspace_type: Application
